import type { Exercise } from './types'
import {
  Exercise1,
  Exercise2,
  Exercise3,
  Exercise4,
  Exercise5,
} from './components/exercises/BasicExercises'
import {
  Exercise6,
  Exercise7,
  Exercise8,
  Exercise9,
  Exercise10,
} from './components/exercises/IntermediateExercises'
import {
  Exercise11,
  Exercise12,
  Exercise13,
  Exercise14,
  Exercise15,
  Exercise16,
  Exercise17,
  Exercise18,
  Exercise19,
  Exercise20,
} from './components/exercises/AdvancedExercises'

export const exercises: Exercise[] = [
  {
    id: 1,
    title: 'Basic Button Selection',
    description: 'Find the submit button in this simple login form.',
    difficulty: 'easy',
    targetElement: 'The main action button in the form',
    hints: [
      'Look for a button element',
      'Try using the tag name selector',
      "The button contains text 'Sign In'",
    ],
    validSelectors: [
      'button',
      '//button',
      "//button[text()='Sign In']",
      "button:contains('Sign In')",
    ],
    component: Exercise1,
  },
  {
    id: 2,
    title: 'Active Navigation Link',
    description: 'Select the currently active navigation link.',
    difficulty: 'easy',
    targetElement: "The navigation link that has the 'active' class",
    hints: [
      'Look for an element with a specific class',
      'Use the class selector syntax',
      'The active link is visually different',
    ],
    validSelectors: [
      '.active',
      'a.active',
      '.nav-link.active',
      "//a[@class='nav-link active']",
      "//*[contains(@class, 'active')]",
    ],
    component: Exercise2,
  },
  {
    id: 3,
    title: 'Save Profile Button',
    description: 'Find the button that saves the user profile.',
    difficulty: 'easy',
    targetElement: "The button with ID 'save-profile'",
    hints: [
      'Look for an element with a unique identifier',
      'Use the ID selector syntax',
      'IDs are unique on a page',
    ],
    validSelectors: [
      '#save-profile',
      'button#save-profile',
      "//button[@id='save-profile']",
      "//*[@id='save-profile']",
    ],
    component: Exercise3,
  },
  {
    id: 4,
    title: 'Required Fields in Contact Form',
    description:
      'Find all required input fields specifically within the contact form (not the newsletter form).',
    difficulty: 'easy',
    targetElement: 'Required input elements inside the contact form',
    hints: [
      'Start by targeting the contact form first',
      'Then look for required inputs within that form',
      'Use descendant selectors or XPath axes',
      'The contact form has an ID for easier targeting',
    ],
    validSelectors: [
      '#contact-form input[required]',
      '#contact-form [required]',
      'form#contact-form input[required]',
      "//form[@id='contact-form']//input[@required]",
      "//*[@id='contact-form']//input[@required]",
      "//form[@id='contact-form']//*[@required]",
    ],
    component: Exercise4,
  },
  {
    id: 5,
    title: 'Out of Stock Button',
    description: "Find the button that shows 'Out of Stock'.",
    difficulty: 'easy',
    targetElement: "The button containing the text 'Out of Stock'",
    hints: [
      'Look for text content within an element',
      'Use text-based selectors',
      'The button has different styling',
    ],
    validSelectors: [
      "//button[text()='Out of Stock']",
      "//button[contains(text(), 'Out of Stock')]",
      "button:contains('Out of Stock')",
    ],
    component: Exercise5,
  },
  {
    id: 6,
    title: 'Second Table Row',
    description: 'Select the second row in the data table.',
    difficulty: 'medium',
    targetElement: 'The second data row (not including header)',
    hints: [
      'Use positional selectors',
      'Remember to account for the header row',
      'CSS has nth-child selector',
    ],
    validSelectors: [
      'tbody tr:nth-child(2)',
      'tbody tr:nth-of-type(2)',
      '//tbody/tr[2]',
      '//tr[position()=2 and parent::tbody]',
    ],
    component: Exercise6,
  },
  {
    id: 7,
    title: 'Notification Checkboxes',
    description:
      "Find all checkboxes within the 'Notifications' settings section.",
    difficulty: 'medium',
    targetElement: 'Checkboxes inside the first settings section',
    hints: [
      'Use descendant selectors',
      'Look for the relationship between parent and child elements',
      'The section has specific content',
    ],
    validSelectors: [
      ".settings-section:first-child input[type='checkbox']",
      ".settings-section:nth-child(1) input[type='checkbox']",
      "//div[@class='settings-section'][1]//input[@type='checkbox']",
      "//h4[text()='Notifications']/following-sibling::div//input[@type='checkbox']",
    ],
    component: Exercise7,
  },
  {
    id: 8,
    title: 'Document Files',
    description:
      'Select all files that are documents (not images or spreadsheets).',
    difficulty: 'medium',
    targetElement: "File elements with data-type='document'",
    hints: [
      'Look for elements with specific attribute values',
      'Use attribute value selectors',
      'Documents have a specific data type',
    ],
    validSelectors: [
      "[data-type='document']",
      ".file-name[data-type='document']",
      "//span[@data-type='document']",
      "//*[@data-type='document']",
    ],
    component: Exercise8,
  },
  {
    id: 9,
    title: 'Active Success Status',
    description: 'Find the status card that is both successful and active.',
    difficulty: 'medium',
    targetElement:
      "The status indicator with both 'success' and 'active' classes",
    hints: [
      'Look for elements with multiple classes',
      'Use multiple class selectors',
      'The element has two specific classes',
    ],
    validSelectors: [
      '.status-indicator.success.active',
      '.success.active',
      "//div[@class='status-indicator success active']",
      "//*[contains(@class, 'success') and contains(@class, 'active')]",
    ],
    component: Exercise9,
  },
  {
    id: 10,
    title: 'Visible Error Messages',
    description:
      'Select error messages that are currently visible (not hidden).',
    difficulty: 'medium',
    targetElement: "Error message elements without the 'hidden' class",
    hints: [
      "Look for elements that don't have a specific class",
      'Use negation selectors',
      'Some error messages are hidden',
    ],
    validSelectors: [
      '.error-message:not(.hidden)',
      'div.error-message:not(.hidden)',
      "//div[@class='error-message text-red-600 text-sm mt-1' and not(contains(@class, 'hidden'))]",
      "//div[contains(@class, 'error-message') and not(contains(@class, 'hidden'))]",
    ],
    component: Exercise10,
  },
  {
    id: 11,
    title: 'High Priority News',
    description:
      'Find news items with high priority that are in loaded content.',
    difficulty: 'hard',
    targetElement: "News items with data-priority='high' inside loaded content",
    hints: [
      'Look for nested conditions with multiple attributes',
      'Combine ancestor and attribute selectors',
      'The content section has a data-loaded attribute',
    ],
    validSelectors: [
      "[data-loaded='true'] .news-item[data-priority='high']",
      ".content-section[data-loaded='true'] [data-priority='high']",
      "//div[@data-loaded='true']//div[@data-priority='high']",
      "//div[@class='content-section' and @data-loaded='true']//div[@class='news-item' and @data-priority='high']",
    ],
    component: Exercise11,
  },
  {
    id: 12,
    title: 'Plus Quantity Buttons',
    description:
      'Select all the plus (+) buttons for increasing item quantities.',
    difficulty: 'hard',
    targetElement: "Buttons with class 'plus' inside quantity controls",
    hints: [
      'Look for buttons with specific class and content',
      'The buttons are part of quantity controls',
      'Use both class and text content',
    ],
    validSelectors: [
      '.quantity-btn.plus',
      'button.plus',
      "//button[@class='quantity-btn plus']",
      "//button[contains(@class, 'plus')]",
      "//button[text()='+']",
    ],
    component: Exercise12,
  },
  {
    id: 13,
    title: 'Modal Close Button',
    description: 'Find the close button inside the modal dialog.',
    difficulty: 'hard',
    targetElement: 'The close button within the modal content',
    hints: [
      'Look inside modal-specific containers',
      'The close button has a specific class',
      'Use descendant selectors for modal structure',
    ],
    validSelectors: [
      '.modal-content .modal-close',
      '.modal-header .modal-close',
      "//div[@class='modal-content']//button[@class='modal-close text-gray-500 hover:text-gray-700']",
      "//div[contains(@class, 'modal-header')]//button[contains(@class, 'modal-close')]",
    ],
    component: Exercise13,
  },
  {
    id: 14,
    title: 'Current Step Number',
    description: 'Find the step number of the currently active step.',
    difficulty: 'hard',
    targetElement: 'The step number inside the active step',
    hints: [
      'Look for the active step first',
      'Then find the step number within it',
      'Use descendant relationships',
    ],
    validSelectors: [
      '.step.active .step-number',
      '.active .step-number',
      "//div[@class='step active']//div[@class='step-number bg-blue-600 text-white rounded-full w-8 h-8 flex items-center justify-center']",
      "//div[contains(@class, 'active')]/div[contains(@class, 'step-number')]",
    ],
    component: Exercise14,
  },
  {
    id: 15,
    title: 'Admin Role Badge',
    description: 'Select the role badge for admin users in the table.',
    difficulty: 'hard',
    targetElement: "Role badge elements that contain 'Admin' text",
    hints: [
      'Look for role badges with specific content',
      'Use class and text content selectors',
      'Admin badges have specific styling',
    ],
    validSelectors: [
      '.role-badge.admin',
      "//span[@class='role-badge admin bg-purple-100 text-purple-800 px-2 py-1 rounded']",
      "//span[contains(@class, 'role-badge') and contains(@class, 'admin')]",
      "//span[contains(@class, 'role-badge') and text()='Admin']",
    ],
    component: Exercise15,
  },
  {
    id: 16,
    title: 'Featured Submenu Link',
    description: "Find the 'Featured' link in the Products submenu.",
    difficulty: 'hard',
    targetElement: 'The featured submenu link within the products section',
    hints: [
      'Navigate through nested menu structure',
      'Look for submenu within specific parent',
      'The link has multiple classes',
    ],
    validSelectors: [
      '.submenu .submenu-link.featured',
      '.has-submenu .submenu .featured',
      "//li[contains(@class, 'has-submenu')]//a[contains(@class, 'featured')]",
      "//ul[@class='submenu bg-gray-50']//a[text()='Featured']",
    ],
    component: Exercise16,
  },
  {
    id: 17,
    title: "Today's Date",
    description: 'Select the calendar cell that represents today.',
    difficulty: 'hard',
    targetElement: "The calendar day cell with the 'today' class",
    hints: [
      "Look for a specific day with today's styling",
      'Today has a different appearance',
      'Use the today class selector',
    ],
    validSelectors: [
      '.day.today',
      '.today',
      "//div[@class='day current-month today bg-blue-600 text-white p-2 rounded cursor-pointer']",
      "//div[contains(@class, 'today')]",
    ],
    component: Exercise17,
  },
  {
    id: 18,
    title: 'Bold Formatting Button',
    description: 'Find the bold formatting button in the text editor toolbar.',
    difficulty: 'hard',
    targetElement: "The bold tool button with data-command='bold'",
    hints: [
      'Look in the toolbar area',
      'The button has a data-command attribute',
      'Bold button has specific styling',
    ],
    validSelectors: [
      '.tool-btn.bold',
      "[data-command='bold']",
      ".tool-btn[data-command='bold']",
      "//button[@data-command='bold']",
      "//button[contains(@class, 'bold')]",
    ],
    component: Exercise18,
  },
  {
    id: 19,
    title: 'Completed List Items',
    description: 'Select all list items that have a completed status.',
    difficulty: 'hard',
    targetElement: "List items with data-status='completed'",
    hints: [
      'Look for items with specific status attribute',
      'Completed items have different styling',
      'Use attribute value selectors',
    ],
    validSelectors: [
      ".list-item[data-status='completed']",
      "[data-status='completed']",
      "//div[@data-status='completed']",
      "//div[@class='list-item flex items-center justify-between p-3 border rounded' and @data-status='completed']",
    ],
    component: Exercise19,
  },
  {
    id: 20,
    title: 'Recent Activity Icons',
    description: "Find all activity icons in the dashboard's activity widget.",
    difficulty: 'hard',
    targetElement: 'Activity icons within the activity widget',
    hints: [
      'Look inside the activity widget specifically',
      'Icons have a specific class pattern',
      'Use descendant selectors for widget structure',
    ],
    validSelectors: [
      '.activity-widget .activity-icon',
      '.widget.activity-widget .activity-icon',
      "//div[contains(@class, 'activity-widget')]//div[contains(@class, 'activity-icon')]",
      "//div[@class='widget activity-widget bg-white border rounded-lg p-4 shadow-sm']//div[contains(@class, 'activity-icon')]",
    ],
    component: Exercise20,
  },
]
